---
permalink: /background/
layout:    default
title:     Background
nobio:     true
output: md_document
bibliography: bibliography.bib
---
<!-- After knitting, paste the yaml header above  -->
# Background

I became interested in reproducible research because I was tired of being terrified of my own analysis. I was constantly petrified someone would question my work and ask me to open the black box and verify what I did was correct; in some cases even being asked reproduce a result was terrifying because I knew the convoluted path of data prep and cleaning that I took in arriving at my result. 

I read the book [Reproducable Research with R and RStudio](http://www.amazon.com/Reproducible-Research-Studio-Chapman-Hall/dp/1466572841) by Christopher Gandrud [-@gandrud2013reproducible], and I read a lot of blog posts and tutorials by [Karl Broman](http://kbroman.org/pages/software.html) and [Carl Boettiger](http://www.carlboettiger.info/2012/05/06/research-workflow.html) and I struck out on my own path to execute a reproducible research project from start to finish. The repository for that project is [here](https://github.com/mindymallory/BBOBAS), while I was successful in learning the basics of how r, rmarkdown, knitr, and pandoc combine to make reproducible research possible, you can tell just by looking at the project's Github repository that I failed miserably at making the project reproducible. This is because the repository is totally unorganized, and I am pretty sure I am the only one who could reproduce the results from this project. 

But in that failure, I learned a lot about how a reproducible research project should be organized. I built this template for my future students and for my future self. 

## References
