name:   'Mindy L. Mallory'
url:    'http://mindymallory.github.io'
author: 'Mindy Mallory'

gems:
  - jekyll-seo-tag
  - jekyll-paginate

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'

excerpt_separator: "{{ more }}"

markdown: 'kramdown'
timezone: 'America/Chicago'
highlighter: 'rouge'
