# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mindy L. Mallory
email: mallorym@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
   I analyze prices and risk in commodity, environmental, and natural resource markets.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://mindymallory.github.io/ # the base hostname & protocol for your site
twitter_username: ace_prof
github_username:  mindymallory


# Build settings
markdown: redcarpet
