project:
  type: website
  output-dir: docs

website:
  title: "Mindy L. Mallory"
  description: "Personal website of Mindy Mallory"
  site-url: http://mindymallory.com
  repo-url: https://https://github.com/mindymallory/mindymallory.github.io
  google-analytics: "G-S2TTKQ6NC6"
  open-graph: true
  favicon: favicon.png
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home


format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango
