---
layout: page
title: "Hello World!"
---

I have been hesitant to blog. Preferring to prioritize my time on research that was targeted at peer-reviewed journal articles, taking time to blog previously seemed like a distraction and dangerous to my prospects of securing tenure. 

Now, my tenure case is pending a vote by the campus committee (and final approval by the Board of Trustees), with a couple of positive votes behind me at the department and college level. I find myself contemplating next my next steps. While I have had some success publishing, I would like my work to have more impact beyond acedemic audiences. This blog is an effort toward that goal. So what should readers expect to find in this blog?

## Research

The time between beginning a research project to seeing the final publication in print is frustratingly long. While the peer-review process is (an attempt) to keep quality of academic research high---and it definitely has a valuable place in the process---the timeline is simply not always conducive to impacting stakeholders', policymakers', and others' decisions. By the time your article is in print, sometimes the issue of the day has been decided for bettor or worse. 

This blog will communicate research findings that a broad audience would find interesting or useful. Often, details and results that are interesting but do not quite fit into the full academic paper destined for publication. I will also post summaries of my recently published work.

## Teaching

Teaching about commodity markets and price analysis to undergraduates means I often need to dig up (or create) resources for my students. The more interesting ones I will archive here as well.

## Other

Who knows what other topics I may be compelled to offer my take on as well. 



