---
title: "Publications"
output: md_document
bibliography: mypubs.bib
csl: year-ajae.txt
nocite: |
  @trujillo2012volatility, @ando2012optimal, @mallory2012market, @mallory2011crop, @du2009welfare, @yu2014exchange, @mallory2012food,
  @irwin2011could, @sherrick2013s, @mallory2012testing, @mallory2011alternative, @mallory2014perils, @ando2012reply, @paulson2013determinants,
  @yu2015optimal, @mallory2015cost, @mallory2011coordination
---



<!--
To update this page:

1. Update mypubs.bib
2. Add the key to the nocite parameter in the YAML header
3. Knit
4. Front matter in .md document is missing so open publications.md in the root directory and type
---
layout: page
title: Publications
comments: False
permalink: /publications/
---

-->

[pdf](http://mindymallory.github.io/publications.pdf)


# Articles in Peer-Reviewed Journals
\noindent
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}


<!--
To generate pdf: 

1. Change YAML "output: pdf_document"
2. Comment out the .md r chunk at the bottom
3. Uncomment the .pdf r chunk at the bottom
-->

<!--
```{r, include=FALSE}
  # For .md 
  # This adds the file to the root so Jekyll will include it in the site build
  # file.rename(from="C:/Users/mallorym/Documents/GitHub/mindymallory.github.io/_drafts/publications.md", 
   #            to="C:/Users/mallorym/Documents/GitHub/mindymallory.github.io/publications.md")
```
-->

<!--
```{r, include=FALSE}
  # For .pdf 
  # This adds the file to the root so Jekyll will include it in the site build
  # file.rename(from="C:/Users/mallorym/Documents/GitHub/mindymallory.github.io/_drafts/publications.pdf", 
   #            to="C:/Users/mallorym/Documents/GitHub/mindymallory.github.io/publications.pdf")
```
-->